import { ArrowUpRight, BatteryCharging, CircleHelp, Clock3, CreditCard, Fuel, Menu, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";
import "./_group.css";

export function EarningsCommand() {
  const [online,setOnline]=useState(true); const [claimed,setClaimed]=useState(false);
  return <main className="myride-preview"><div className="scroll-view" style={{background:"#111718"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div className="brand">My <em>Ride</em><small>DRIVER BUSINESS DASHBOARD</small></div><button className="icon-btn"><Menu size={16}/></button></header>
    <section style={{marginTop:24}}><div className="eyebrow">Thursday, 14 March · Lahore</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginTop:4}}><h1 style={{fontSize:39,letterSpacing:"-.08em"}}>PKR 4,860</h1><TrendingUp color="var(--cyan)" size={22}/></div><p className="subtle">Today’s net earnings <span style={{color:"var(--cyan)"}}>↑ 12% vs last Thursday</span></p></section>
    <div className="glass" style={{marginTop:19,borderRadius:17,padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div className="eyebrow">Daily target</div><b style={{fontSize:19}}>PKR 6,000</b></div><b className="mono" style={{color:"var(--cyan)",fontSize:14}}>81%</b></div><div style={{height:8,background:"#2b3738",borderRadius:8,marginTop:12}}><div style={{width:"81%",height:"100%",borderRadius:8,background:"var(--cyan)"}}/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:8}}><span className="subtle">PKR 1,140 to go</span><span className="subtle">2h 18m left</span></div></div>
    <div className="metric-row" style={{marginTop:9}}><div className="metric"><Clock3 size={15} color="var(--yellow)"/><b>6h 42m</b><span>ACTIVE TIME</span></div><div className="metric"><ArrowUpRight size={15} color="var(--cyan)"/><b>18 rides</b><span>COMPLETED</span></div><div className="metric"><Fuel size={15} color="var(--coral)"/><b>PKR 920</b><span>FUEL EST.</span></div></div>
    <div className="section-head"><h2>Work switch</h2><span>{online?"Accepting work":"Paused"}</span></div><div className="glass" style={{borderRadius:15,padding:13,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><b>{online?"Online in Lahore":"Offline"}</b><p className="subtle">Long range + short range rides</p></div><button className={`toggle ${online?"on":""}`} onClick={()=>setOnline(!online)}><i/></button></div>
    <div className="section-head"><h2>Ready next</h2><span style={{color:"var(--cyan)"}}>2 offers nearby</span></div><div className="glass" style={{borderRadius:17,padding:14,borderColor:"rgba(116,224,209,.35)"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div className="eyebrow" style={{color:"var(--cyan)"}}>Suggested ride</div><b style={{fontSize:18}}>DHA Phase 5 → Liberty</b></div><b style={{color:"var(--yellow)"}}>PKR 510</b></div><p className="subtle" style={{marginTop:7}}>9.1 km · 22 min · 3 min away</p><button className="primary" style={{marginTop:12}} onClick={()=>setClaimed(true)}>{claimed?"Ride reserved":"View and claim offer"}</button></div>
    <div className="section-head"><h2>Wallet health</h2><button className="icon-btn" style={{width:26,height:26}}><WalletCards size={14}/></button></div><div className="glass" style={{borderRadius:15,padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><span className="subtle">Available to withdraw</span><b>PKR 12,480</b></div><div style={{display:"flex",justifyContent:"space-between",marginTop:11}}><span className="subtle">Next settlement</span><span>Tomorrow · 10:00</span></div><button className="secondary" style={{marginTop:12}}>Open wallet</button></div>
    <div style={{display:"flex",gap:9,marginTop:16}}><button className="secondary"><CreditCard size={14}/> Payments</button><button className="secondary"><CircleHelp size={14}/> Help desk</button></div>
  </div></main>
}