import { AlertTriangle, ChevronRight, Crosshair, Gauge, MapPin, Phone, Radio, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import "./_group.css";

export function RoadCockpit() {
  const [online,setOnline]=useState(true); const [decision,setDecision]=useState<"open"|"accepted"|"declined">("open");
  return <main className="myride-preview" style={{minHeight:"720px"}}>
    <div className="map-surface"><div className="map-road"/><div className="map-road two"/><span className="map-label" style={{left:20,top:280}}>Canal Bank Rd</span><span className="map-label" style={{right:25,top:125}}>Wapda Town</span><span className="map-pin pick" style={{left:"22%",top:"37%"}}/><div className="map-car" style={{left:"64%",top:"50%"}}/></div>
    <div style={{position:"relative",zIndex:4,padding:"16px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div className="brand">My <em>Ride</em><small>ROAD COCKPIT / LHR</small></div><button className="icon-btn" onClick={()=>setOnline(!online)}><Radio size={16}/></button></div>
      <div className="glass" style={{marginTop:16,borderRadius:16,padding:"11px 13px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",gap:9,alignItems:"center"}}><span style={{width:9,height:9,borderRadius:"50%",background:online?"var(--cyan)":"var(--coral)"}}/><div><b style={{fontSize:13}}>{online?"AVAILABLE FOR DISPATCH":"PAUSED"}</b><div className="subtle">{online?"3 nearby requests":"Tap to resume"}</div></div></div><button className={`toggle ${online?"on":""}`} onClick={()=>setOnline(!online)}><i/></button></div>
      {decision==="open"&&online?<div className="glass" style={{marginTop:142,borderRadius:22,padding:16,borderColor:"rgba(245,204,104,.65)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div className="eyebrow" style={{color:"var(--yellow)"}}><AlertTriangle size={12} style={{verticalAlign:"middle"}}/> PRIORITY OFFER</div><b className="mono" style={{color:"var(--yellow)"}}>00:12</b></div><h1 style={{fontSize:26,letterSpacing:"-.06em",marginTop:8}}>PKR 780</h1><p className="subtle">Airport Road → Model Town</p><div className="metric-row" style={{marginTop:14}}><div className="metric"><b>14.2 km</b><span>TRIP</span></div><div className="metric"><b>6 min</b><span>TO PICKUP</span></div><div className="metric"><b>4.9</b><span>RIDER RATING</span></div></div><div style={{display:"flex",gap:8,marginTop:13}}><button className="secondary" onClick={()=>setDecision("declined")}><X size={14}/> Skip</button><button className="primary" onClick={()=>setDecision("accepted")}>Take this ride <ChevronRight size={15} style={{verticalAlign:"middle"}}/></button></div></div>:<div className="glass" style={{marginTop:280,borderRadius:18,padding:16,textAlign:"center"}}>{decision==="accepted"?<><ShieldCheck color="var(--cyan)" size={25}/><h2 style={{marginTop:8}}>Pickup locked in</h2><p className="subtle">Navigate to Airport Road · 6 min</p><button className="primary" style={{marginTop:13}}>Start navigation</button></>:<><Gauge color="var(--dim)" size={25}/><h2 style={{marginTop:8}}>Offer passed</h2><p className="subtle">Scanning the next best ride in Lahore</p></>}</div>}
      <div className="glass" style={{marginTop:10,borderRadius:14,padding:"10px 12px",display:"flex",justifyContent:"space-between"}}><span className="subtle"><Crosshair size={13}/> Demand pulse</span><b style={{color:"var(--cyan)",fontSize:12}}>High · Gulberg</b></div>
    </div>
  </main>
}