// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/driver-wallet/DriverWalletVariant.tsx": () => import("../components/mockups/driver-wallet/DriverWalletVariant.tsx"),
  "./components/mockups/myride-driver-dashboard/Current.tsx": () => import("../components/mockups/myride-driver-dashboard/Current.tsx"),
  "./components/mockups/myride-driver-dashboard/EarningsCommand.tsx": () => import("../components/mockups/myride-driver-dashboard/EarningsCommand.tsx"),
  "./components/mockups/myride-driver-dashboard/FocusMode.tsx": () => import("../components/mockups/myride-driver-dashboard/FocusMode.tsx"),
  "./components/mockups/myride-driver-dashboard/RoadCockpit.tsx": () => import("../components/mockups/myride-driver-dashboard/RoadCockpit.tsx"),
  "./components/mockups/myride-customer-dashboard/Current.tsx": () => import("../components/mockups/myride-customer-dashboard/Current.tsx"),
  "./components/mockups/myride-customer-dashboard/JourneyHub.tsx": () => import("../components/mockups/myride-customer-dashboard/JourneyHub.tsx"),
  "./components/mockups/myride-customer-dashboard/MapCommand.tsx": () => import("../components/mockups/myride-customer-dashboard/MapCommand.tsx"),
  "./components/mockups/myride-customer-dashboard/TripConcierge.tsx": () => import("../components/mockups/myride-customer-dashboard/TripConcierge.tsx")
};
