import "./_group.css";
import { useState } from "react";
import { ArrowUpRight, Bookmark, CarFront, ChevronRight, Clock3, House, MapPin, Plus, ShieldCheck, WalletCards } from "lucide-react";

const recent = [["Gulberg III", "DHA Phase 5", "PKR 620", "Today, 6:42 PM"], ["Johar Town", "Packages Mall", "PKR 485", "Yesterday, 9:14 AM"], ["Airport Road", "Model Town", "PKR 720", "12 Aug, 3:05 PM"]];
export function JourneyHub() {
  const [notice, setNotice] = useState(""); const [saved, setSaved] = useState(["Home", "Work"]); const notify = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(""), 1600); };
  return <main className="myride-shell" style={{ background: "#101719", overflow: "auto" }}><div className="scroll-page"><header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 24 }}><div><div className="wordmark">My <span>Ride</span></div><div className="small-label" style={{ marginTop: 3 }}>Customer · your mobility hub</div></div><div className="avatar">AK</div></header>
    <section style={{ padding: 17, borderRadius: 18, background: "#e7d8a7", color: "#202825", position: "relative", overflow: "hidden" }}><div style={{ position: "absolute", right: -15, top: -25, width: 120, height: 120, border: "1px solid #bfae78", borderRadius: "50%" }} /><div className="small-label" style={{ color: "#6f663f" }}>Active journey</div><h1 style={{ fontSize: 22, letterSpacing: "-.05em", margin: "7px 0 14px" }}>A ride worth<br />leaving on time for.</h1><div className="journey-row" style={{ borderColor: "#cbbd91" }}><CarFront size={16} /><div style={{ flex: 1 }}><strong style={{ fontSize: 13 }}>Rehan · arriving in 04 min</strong><small style={{ color: "#6f663f" }}>White Toyota Corolla · LEB-23-418</small></div><ArrowUpRight size={17} /></div><div style={{ display: "flex", gap: 7, marginTop: 14 }}><button onClick={() => notify("Live trip opened")} className="primary-button" style={{ flex: 2, background: "#202825", color: "#f4f0e7", padding: 11 }}>Open live trip</button><button onClick={() => notify("Safety contact notified")} className="ghost-button" style={{ flex: 1, padding: 8, borderColor: "#aaa074", color: "#202825" }}><ShieldCheck size={15} /></button></div></section>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", margin: "25px 0 11px" }}><h2 className="section-title" style={{ margin: 0 }}>Start a journey</h2><button onClick={() => notify("Booking path opened")} style={{ border: 0, background: "transparent", color: "var(--signal)", fontSize: 11 }}>Book now <ChevronRight size={13} style={{ verticalAlign: "middle" }} /></button></div>
    <button onClick={() => notify("New ride form opened")} style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: 15, border: "1px solid var(--line)", borderRadius: 15, background: "#171e20", color: "var(--ink)", textAlign: "left" }}><div style={{ display: "grid", placeItems: "center", width: 35, height: 35, borderRadius: 10, background: "#293334", color: "var(--signal)" }}><Plus size={17} /></div><div style={{ flex: 1 }}><strong style={{ display: "block", fontSize: 13 }}>Where to next?</strong><span style={{ color: "var(--muted)", fontSize: 11 }}>Pickup from your current location</span></div><ChevronRight size={16} color="var(--muted)" /></button>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", margin: "25px 0 11px" }}><h2 className="section-title" style={{ margin: 0 }}>Saved places</h2><button onClick={() => setSaved([...saved, "New place"])} style={{ border: 0, background: "transparent", color: "var(--signal)", fontSize: 11 }}><Plus size={13} /> Add</button></div><div style={{ display: "flex", gap: 9, overflow: "auto" }}>{saved.map((place, i) => <button key={`${place}-${i}`} onClick={() => notify(`${place} selected`)} className="journey-card" style={{ minWidth: 117, padding: 12, textAlign: "left", color: "var(--ink)" }}><div style={{ display: "flex", justifyContent: "space-between" }}><div className="chip">{i % 2 === 0 ? <House size={12} /> : <Bookmark size={12} />}</div><ChevronRight size={13} color="var(--muted)" /></div><strong style={{ display: "block", marginTop: 12, fontSize: 12 }}>{place}</strong><small style={{ color: "var(--muted)", fontSize: 10 }}>{i === 0 ? "Model Town" : "Gulberg III"}</small></button>)}</div>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", margin: "25px 0 11px" }}><h2 className="section-title" style={{ margin: 0 }}>Recent travel</h2><button onClick={() => notify("Full ride history opened")} style={{ border: 0, background: "transparent", color: "var(--signal)", fontSize: 11 }}>See all</button></div><div className="journey-card">{recent.map(([from, to, fare, date]) => <div className="journey-row" key={date}><div className="journey-icon"><MapPin size={15} /></div><div style={{ flex: 1 }}><p>{from} → {to}</p><small><Clock3 size={10} style={{ verticalAlign: "middle" }} /> {date}</small></div><strong className="mono" style={{ fontSize: 10 }}>{fare}</strong></div>)}</div>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 9, marginTop: 12 }}><button className="ghost-button" style={{ padding: 12, color: "var(--ink)" }} onClick={() => notify("Wallet opened")}><WalletCards size={14} /> Wallet</button><button className="ghost-button" style={{ padding: 12, color: "var(--ink)" }} onClick={() => notify("Trusted safety settings opened")}><ShieldCheck size={14} /> Safety</button></div>
  </div>{notice && <div className="toast">{notice}</div>}</main>;
}