import "./_group.css";
import { useState } from "react";
import { Car, Crosshair, LocateFixed, MapPin, Menu, Navigation, Phone, ShieldCheck, SlidersHorizontal } from "lucide-react";

const options = [["Mini", "PKR 480", "2 min"], ["Sedan", "PKR 620", "4 min"], ["Highroof", "PKR 1,150", "7 min"]];
export function MapCommand() {
  const [active, setActive] = useState(1); const [mode, setMode] = useState<"pickup" | "dropoff">("pickup"); const [booked, setBooked] = useState(false); const [notice, setNotice] = useState("");
  const ping = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(""), 1700); };
  return <main className="myride-shell" style={{ position: "relative", height: "100dvh" }}><section className="map-grid" style={{ backgroundColor: "#18292b" }}><div className="route-line" style={{ left: "48%", top: "13%", height: "66%", transform: "rotate(-16deg)", background: "#d9b74d" }} /><div className="map-pin pickup" style={{ left: "45%", top: "27%", background: "#d9b74d" }}><Crosshair size={13} /></div><div className="map-pin dropoff" style={{ right: "16%", bottom: "25%" }}><MapPin size={13} /></div><div className="map-label one">Bahria Town</div><div className="map-label two">Canal Road</div><div className="map-label three">DHA Phase 6</div></section>
    <header className="topbar"><div><div className="wordmark">My <span>Ride</span></div><div className="small-label" style={{ marginTop: 2 }}>Customer control</div></div><div style={{ display: "flex", gap: 8 }}><button className="icon-button" onClick={() => ping("Centering on your location")}><Crosshair size={16} /></button><button className="icon-button" onClick={() => ping("Menu opened")}><Menu size={17} /></button></div></header>
    <div style={{ position: "absolute", top: 90, left: 16, right: 16, zIndex: 3, display: "flex", gap: 7 }}><button onClick={() => setMode("pickup")} style={{ flex: 1, padding: 10, border: `1px solid ${mode === "pickup" ? "#d9b74d" : "var(--line)"}`, borderRadius: 10, background: "#121b1cd9", color: "var(--ink)", textAlign: "left", fontSize: 11 }}><span className="small-label">Pickup</span><br />Packages Mall</button><button onClick={() => setMode("dropoff")} style={{ flex: 1, padding: 10, border: `1px solid ${mode === "dropoff" ? "#d9b74d" : "var(--line)"}`, borderRadius: 10, background: "#121b1cd9", color: "var(--ink)", textAlign: "left", fontSize: 11 }}><span className="small-label">Drop-off</span><br />DHA Phase 6</button></div>
    <section className="bottom-panel" style={{ maxHeight: "53%" }}><div className="grabber" /><div className="panel-pad"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div className="small-label">Pickup certainty</div><h2 style={{ margin: "5px 0 0", fontSize: 17 }}>Packages Mall main gate</h2></div><button className="icon-button" onClick={() => ping("Pickup pin moved")}><LocateFixed size={16} /></button></div><div style={{ display: "flex", gap: 6, margin: "11px 0 13px" }}><span className="chip"><Crosshair size={12} /> Pin is precise</span><span className="chip" style={{ background: "#1e2927", color: "#a5d9bd" }}><ShieldCheck size={12} /> Safe pickup spot</span></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end" }}><div><div className="small-label">Choose quickly</div><div style={{ marginTop: 3, color: "var(--muted)", fontSize: 11 }}>6.8 km to DHA Phase 6</div></div><button className="icon-button" onClick={() => ping("Fare options adjusted")}><SlidersHorizontal size={15} /></button></div><div className="vehicle-row">{options.map((item, i) => <button key={item[0]} className={`vehicle ${active === i ? "selected" : ""}`} style={{ minWidth: 100 }} onClick={() => setActive(i)}><Car size={16} /><strong>{item[0]}</strong><span>{item[1]} · {item[2]}</span></button>)}</div><div className="fare-line"><span className="small-label">Authoritative quote</span><span className="fare-value">{options[active][1]}</span></div><button className="primary-button" onClick={() => setBooked(true)}>{booked ? "Driver search started" : "Request ride"} <Navigation size={15} /></button></div>{booked && <div style={{ padding: "0 16px 16px", color: "var(--green)", fontSize: 11 }}>Searching near Packages Mall · usually under 4 min <button className="ghost-button" style={{ float: "right", padding: "4px 7px", color: "var(--muted)" }} onClick={() => setBooked(false)}>Undo</button></div>}<div className="tabs"><button className="tab" onClick={() => ping("Your rides opened")}>Rides</button><button className="tab" onClick={() => ping("Support opened")}>Support</button><button className="tab" onClick={() => ping("Emergency contacts ready")}><Phone size={13} /> Emergency</button></div></section>{notice && <div className="toast">{notice}</div>}</main>;
}