import "./_group.css";
import { useState } from "react";
import { ArrowRight, CarFront, Check, ChevronDown, CircleHelp, CreditCard, LocateFixed, MapPin, ShieldCheck, Sparkles, WalletCards } from "lucide-react";

const rideTypes = [{ name: "Economy", detail: "Comfortable, everyday rides", fare: "PKR 540", icon: CarFront }, { name: "Executive", detail: "A little more room", fare: "PKR 780", icon: CarFront }, { name: "Family", detail: "Up to 6 passengers", fare: "PKR 1,040", icon: CarFront }];
export function TripConcierge() {
  const [step, setStep] = useState(1); const [selected, setSelected] = useState(0); const [payment, setPayment] = useState("Cash"); const [notice, setNotice] = useState("");
  const next = () => { if (step < 3) setStep(step + 1); else setNotice("Ride request sent — finding your driver"); };
  return <main className="myride-shell" style={{ background: "#f1ede5", color: "#202825", minHeight: "100dvh", overflow: "auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "22px 18px 15px", background: "#f1ede5" }}><div><div className="wordmark" style={{ color: "#202825" }}>My <span>Ride</span></div><div className="small-label" style={{ color: "#727873", marginTop: 3 }}>Customer · Lahore</div></div><div className="avatar">AK</div></header>
    <div style={{ padding: "4px 18px 23px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end" }}><div><div className="small-label" style={{ color: "#727873" }}>Good evening, Areeba</div><h1 style={{ margin: "6px 0 0", fontSize: 27, letterSpacing: "-.06em" }}>Let’s get you<br /><span style={{ color: "#b18025" }}>there.</span></h1></div><div style={{ display: "flex", gap: 5 }}>{[1,2,3].map(n => <span key={n} style={{ width: n === step ? 24 : 7, height: 7, borderRadius: 8, background: n <= step ? "#b18025" : "#d1ccc1", transition: "width .2s" }} />)}</div></div></div>
    <section style={{ margin: "0 12px", borderRadius: 20, background: "#fffdf8", boxShadow: "0 8px 26px rgba(52,45,30,.08)", padding: 18 }}>
      {step === 1 && <><div className="small-label" style={{ color: "#727873" }}>Step 01 · route</div><h2 style={{ margin: "7px 0 16px", fontSize: 18 }}>Where should we pick you up?</h2><div style={{ display: "grid", gap: 10 }}><label className="field"><i style={{ color: "#5f9ebf", background: "#e5f1f5" }}><LocateFixed size={13} /></i><input defaultValue="Packages Mall, Walton Road" style={{ background: "#f6f3ed", color: "#202825", borderColor: "#e3ded2" }} /></label><label className="field"><i style={{ color: "#b18025", background: "#f8edd0" }}><MapPin size={13} /></i><input defaultValue="Liberty Market, Gulberg III" style={{ background: "#f6f3ed", color: "#202825", borderColor: "#e3ded2" }} /></label></div><button className="ghost-button" style={{ width: "100%", marginTop: 12, padding: 11, color: "#727873", borderColor: "#e3ded2" }} onClick={() => setNotice("Saved places are coming up")}><Sparkles size={14} /> Use a saved place</button></>}
      {step === 2 && <><div className="small-label" style={{ color: "#727873" }}>Step 02 · choose a ride</div><h2 style={{ margin: "7px 0 14px", fontSize: 18 }}>Your comfort, your call.</h2><div style={{ display: "grid", gap: 9 }}>{rideTypes.map((ride, i) => <button key={ride.name} onClick={() => setSelected(i)} style={{ display: "flex", alignItems: "center", gap: 12, padding: 12, textAlign: "left", border: `1px solid ${selected === i ? "#b18025" : "#e3ded2"}`, borderRadius: 13, background: selected === i ? "#fbf3dc" : "#fffdf8", color: "#202825" }}><div style={{ display: "grid", placeItems: "center", width: 35, height: 35, borderRadius: 10, background: selected === i ? "#e6c875" : "#eeece5" }}><ride.icon size={17} /></div><div style={{ flex: 1 }}><strong style={{ display: "block", fontSize: 13 }}>{ride.name}</strong><span style={{ display: "block", color: "#727873", fontSize: 10, marginTop: 2 }}>{ride.detail}</span></div><strong className="mono" style={{ fontSize: 11 }}>{ride.fare}</strong>{selected === i && <Check size={15} color="#b18025" />}</button>)}</div></>}
      {step === 3 && <><div className="small-label" style={{ color: "#727873" }}>Step 03 · review</div><h2 style={{ margin: "7px 0 14px", fontSize: 18 }}>Everything look right?</h2><div className="journey-card" style={{ background: "#f6f3ed", borderColor: "#e3ded2" }}><div className="journey-row"><LocateFixed size={15} className="journey-icon" style={{ color: "#5f9ebf" }} /><div><small>Pickup</small><p>Packages Mall, Walton Road</p></div></div><div className="journey-row"><MapPin size={15} className="journey-icon" style={{ color: "#b18025" }} /><div><small>Drop-off</small><p>Liberty Market, Gulberg III</p></div></div><div style={{ display: "flex", justifyContent: "space-between", paddingTop: 14 }}><span style={{ color: "#727873", fontSize: 12 }}>Quoted fare · 6.8 km</span><strong className="mono" style={{ color: "#b18025" }}>PKR {rideTypes[selected].fare.replace("PKR ", "")}</strong></div></div><button onClick={() => setPayment(payment === "Cash" ? "Card •• 48" : "Cash")} className="pay-select" style={{ width: "100%", color: "#202825", background: "#fffdf8", borderColor: "#e3ded2", marginTop: 10 }}><span>{payment === "Cash" ? <WalletCards size={14} /> : <CreditCard size={14} />} {payment}</span><ChevronDown size={14} /></button></>}
      <button className="primary-button" style={{ marginTop: 17, background: "#202825", color: "#f5f0e7" }} onClick={next}>{step === 3 ? "Request this ride" : "Continue"} <ArrowRight size={15} /></button>
    </section>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, margin: 12 }}><button className="ghost-button" style={{ padding: 13, color: "#202825", borderColor: "#d8d1c3", background: "#e9e4da" }} onClick={() => setNotice("Safety center opened")}><ShieldCheck size={14} /> Safety</button><button className="ghost-button" style={{ padding: 13, color: "#202825", borderColor: "#d8d1c3", background: "#e9e4da" }} onClick={() => setNotice("Help center opened")}><CircleHelp size={14} /> Help</button></div>
    {notice && <div className="toast" style={{ background: "#202825" }}>{notice}</div>}
  </main>;
}